import Link from "next/link";
import "./global.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><div className="navbar bg-base-100 shadow-sm">
  <div className="flex-1">
    <Link  href="/" className="btn btn-ghost text-xl">ThumbnailsAI</Link>
  </div>
  <div className="flex-none">
    <ul className="menu menu-horizontal px-1">
    <li><Link href="/register">Register</Link></li>
      <li><Link href="/login">Login</Link></li>
      
    </ul>
  </div>
</div>
        {/* <header>ThumbnailsAI</header> */}
        {children}
      </body>
    </html>
  )
}
